# Generated by Django 4.2.3 on 2023-08-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(blank=True, max_length=32, null=True)),
                ('apellidoProducto', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
